In [1]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import yfinance as yf
import numpy as np
from functools import reduce

## Stock Feature Selection: Adj Close, Volume, RSI, ATR

In [35]:
tickers = pd.read_csv('tickers.csv')
tickers.sort_values(by='Market Cap', ascending=False, inplace=True)
top18_tickers = tickers[:20]
top18_tickers.reset_index(inplace=True)
top18_tickers = top18_tickers.drop([7,8])
stocks = top18_tickers['Symbol'].to_list()
start_date = '2013-01-01'
end_date = '2019-01-01'
data = yf.download("AAPL", start=start_date, end=end_date)
data = data.reset_index()
dates = data['Date']

[*********************100%%**********************]  1 of 1 completed


In [44]:
def get_log_returns(list_of_stocks_tickers, start_date, end_date, interval='1d'):
    stocks = list()
    for ticker in list_of_stocks_tickers:
        data = yf.download(ticker, start=start_date, end=end_date, interval=interval)
        data = {ticker: np.log(data['Adj Close']) - np.log(data['Adj Close'].shift(1))}
        log_return = pd.DataFrame(data=data)
        stocks.append(log_return)
    all_stocks = reduce(lambda df1, df2: pd.merge(df1, df2, on='Date'), stocks)
    all_stocks['Date'] = log_return.index
    return all_stocks

In [45]:
stocks

['AAPL',
 'MSFT',
 'GOOG',
 'GOOGL',
 'AMZN',
 'NVDA',
 'TSLA',
 'META',
 'HSBC',
 'LLY',
 'TSM',
 'V',
 'UNH',
 'XOM',
 'JPM',
 'WMT',
 'NVO',
 'JNJ']

In [46]:
returns = get_log_returns(stocks, start_date, end_date)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%*******

In [47]:
returns

AAPL      MSFT      GOOG     GOOGL      AMZN      NVDA  \
Date                                                                     
2013-01-02       NaN       NaN       NaN       NaN       NaN       NaN   
2013-01-03 -0.012703 -0.013487  0.000581  0.000581  0.004537  0.000786   
2013-01-04 -0.028250 -0.018893  0.019568  0.019568  0.002589  0.032460   
2013-01-07 -0.005900 -0.001872 -0.004373 -0.004373  0.035295 -0.029323   
2013-01-08  0.002688 -0.005259 -0.001975 -0.001975 -0.007778 -0.022170   
...              ...       ...       ...       ...       ...       ...   
2018-12-24 -0.026215 -0.042635 -0.003395 -0.006660 -0.024613 -0.019404   
2018-12-26  0.068053  0.066078  0.062769  0.062189  0.090254  0.046284   
2018-12-27 -0.006511  0.006146  0.004243  0.004808 -0.006315 -0.014607   
2018-12-28  0.000512 -0.007838 -0.006535 -0.005925  0.011144  0.018730   
2018-12-31  0.009619  0.011685 -0.001418 -0.001645  0.016074 -0.001123   

                TSLA      META      HSBC       LLY       TSM         V  \
Date                                                                     
2013-01-02       NaN       NaN       NaN       NaN       NaN       NaN   
2013-01-03 -0.016826 -0.008248 -0.017466  0.004232 -0.000552  0.000772   
2013-01-04 -0.010699  0.035029  0.006167  0.036339 -0.007212  0.008134   
2013-01-07 -0.001746  0.022689  0.001489 -0.001359 -0.014583  0.007119   
2013-01-08 -0.019407 -0.012312 -0.010847  0.007546 -0.009080  0.009267   
...              ...       ...       ...       ...       ...       ...   
2018-12-24 -0.079305 -0.007148 -0.004695 -0.024704 -0.011831 -0.020571   
2018-12-26  0.098877  0.078417  0.021079  0.039851  0.040810  0.067497   
2018-12-27 -0.031020  0.002531 -0.012938  0.016073  0.000544  0.013576   
2018-12-28  0.054598 -0.009861  0.009050  0.011537  0.009740 -0.008139   
2018-12-31 -0.003210 -0.015968  0.000974  0.013222 -0.006212  0.007608   

                 UNH       XOM       JPM       WMT       NVO       JNJ  \
Date                                                                     
2013-01-02       NaN       NaN       NaN       NaN       NaN       NaN   
2013-01-03 -0.047883 -0.001805 -0.002018 -0.006375 -0.002898 -0.001413   
2013-01-04  0.001922  0.004619  0.017570  0.003772  0.005907  0.011386   
2013-01-07  0.000000 -0.011646  0.001101 -0.009603  0.003420 -0.002098   
2013-01-08 -0.013335  0.006236  0.001980  0.002774  0.009775  0.000140   
...              ...       ...       ...       ...       ...       ...   
2018-12-24 -0.022917 -0.039068 -0.021792 -0.015149 -0.011077 -0.041851   
2018-12-26  0.043720  0.046673  0.040622  0.052103  0.024254  0.031018   
2018-12-27  0.010709  0.004361  0.011192  0.012967  0.011472  0.005509   
2018-12-28  0.001097 -0.011232 -0.002166  0.005879  0.005250 -0.001100   
2018-12-31  0.011628  0.000293  0.008126  0.011011  0.005223  0.013889   

                 Date  
Date                   
2013-01-02 2013-01-02  
2013-01-03 2013-01-03  
2013-01-04 2013-01-04  
2013-01-07 2013-01-07  
2013-01-08 2013-01-08  
...               ...  
2018-12-24 2018-12-24  
2018-12-26 2018-12-26  
2018-12-27 2018-12-27  
2018-12-28 2018-12-28  
2018-12-31 2018-12-31  

[1510 rows x 19 columns]

In [48]:
def calculate_rsi(prices, n=14):
    deltas = np.diff(prices)
    seed = deltas[:n+1]
    up = seed[seed >= 0].sum()/n
    down = -seed[seed < 0].sum()/n
    rs = up/down
    rsi = np.zeros_like(prices)
    rsi[:n] = 100. - 100./(1.+rs)

    for i in range(n, len(prices)):
        delta = deltas[i-1]  # The diff is 1 shorter

        if delta > 0:
            upval = delta
            downval = 0.
        else:
            upval = 0.
            downval = -delta

        up = (up*(n-1) + upval)/n
        down = (down*(n-1) + downval)/n

        rs = up/down
        rsi[i] = 100. - 100./(1.+rs)

    return rsi

In [49]:
def calculate_rsi(data, period=14):
    # Calculate price differences
    price_diff = np.diff(data)
    
    # Calculate initial seed values
    seed = price_diff[:period + 1]
    positive_seed = seed[seed >= 0].sum()
    negative_seed = -seed[seed < 0].sum()
    
    # Calculate initial RS and RSI
    initial_rs = positive_seed / negative_seed
    initial_rsi = 100 - 100 / (1 + initial_rs)
    
    # Initialize up and down values
    up = positive_seed / period
    down = negative_seed / period
    
    # Initialize RSI array
    rsi = np.zeros_like(data)
    rsi[:period] = initial_rsi

    for i in range(period, len(data)):
        # Calculate delta for the current period
        delta = price_diff[i - 1]
        
        if delta > 0:
            upval = delta
            downval = 0.
        else:
            upval = 0.
            downval = -delta
        
        # Update up and down values
        up = (up * (period - 1) + upval) / period
        down = (down * (period - 1) + downval) / period
        
        # Calculate RS and RSI for the current period
        current_rs = up / down
        rsi[i] = 100 - 100 / (1 + current_rs)

    return rsi


In [50]:
def calculate_atr(data, period=14):
    data = np.array(data)
    
    high = data[:, 0]
    low = data[:, 1]
    close = data[:, 2]
    
    tr = np.maximum(high - low, np.abs(high - np.roll(close, 1)), np.abs(low - np.roll(close, 1)))
    
    atr = np.zeros_like(tr)
    atr[period] = np.mean(tr[:period])
    
    for i in range(period + 1, len(tr)):
        atr[i] = ((period - 1) * atr[i - 1] + tr[i]) / period
    
    return atr

## Model Param

In [51]:
params = {
    "BATCH_SIZE": 50,
    "EPOCHS": 10,
    "LR": 0.00010000,
    "TIME_STEPS": 60
    }

TIME_STEPS = params['TIME_STEPS']
BATCH_SIZE = params['BATCH_SIZE']


def build_timeseries(mat, y_col_index):
    
    dim_0 = mat.shape[0] - TIME_STEPS
    dim_1 = mat.shape[1]

    x = np.zeros((dim_0, TIME_STEPS, dim_1))
    y = np.zeros((dim_0,))

    print("Length of inputs", dim_0)

    for i in range(dim_0):
        x[i] = mat[i:TIME_STEPS+i]
        y[i] = mat[TIME_STEPS+i, y_col_index]

    print("length of time-series - inputs", x.shape)
    print("length of time-series - outputs", y.shape)


    return x, y
     

## Model

In [52]:
pip install keras_tuner

Note: you may need to restart the kernel to use updated packages.


In [53]:
from sklearn.preprocessing import MinMaxScaler
import keras
import tensorflow as tf
from keras.models import Model
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, Input, Activation,concatenate, Attention, Bidirectional,GlobalAveragePooling1D
from keras import optimizers
from keras.preprocessing.sequence import TimeseriesGenerator
from keras.layers import LeakyReLU
import matplotlib.pyplot as plt
import keras_tuner as kt
plt.style.use('fivethirtyeight')
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [57]:
def model_builder(hyperparameters):
    lstm_model = Sequential()
    
    hyperparameters_units = hyperparameters.Int('units', min_value=50, max_value=100, step=TIME_STEPS)
    lstm_model.add(LSTM(units=hyperparameters_units, 
                        input_shape=(x_t.shape[1], x_t.shape[2]), 
                        return_sequences=True,
                        kernel_initializer='he_normal'))
    lstm_model.add(GlobalAveragePooling1D())
    lstm_model.add(Dense(60,activation='relu'))
    lstm_model.add(Dense(20,activation='relu'))
    lstm_model.add(Dropout(0.05))
    lstm_model.add(Dense(1, activation='linear'))
    
    hyperparameters_learning_rate = hyperparameters.Choice('learning_rate', values=[0.01, 0.05, 0.1])
    
    lstm_model.compile(loss='mean_squared_error', optimizer=keras.optimizers.Adam(learning_rate=hyperparameters_learning_rate))
    
    return lstm_model

In [58]:
mse = {}
total_predicted_returns = pd.DataFrame()
for ticker in stocks:
    df = yf.download(ticker, start='2000-01-01', end=end_date, interval='1d')
    df['RSI'] = calculate_rsi(df['Adj Close'])
    df['ATR'] = calculate_atr(df[['High', 'Low', 'Close']])
    stock_returns = returns[[ticker]].reset_index()
    stock_returns['Date'] = stock_returns['Date'].apply(lambda x: x.strftime('%Y-%m-%d'))
    df.reset_index(inplace=True)
    df_stock = df[['RSI', 'ATR', 'Date', 'Volume']]
    stock_returns.Date = pd.to_datetime(stock_returns.Date)
    df_stock.Date = pd.to_datetime(df_stock.Date)
    data = pd.merge(df_stock[['RSI', 'ATR', 'Date', 'Volume']],  stock_returns , on='Date')[1:].rename(columns={ticker : 'Returns'})
    print(data)
    # Split the data we try by years first
    data = data[data['Date'] < '2019-01-01']
    df_train = data[data['Date'] < '2018-01-01']
    predicted_period = data[(data['Date'] >= '2018-01-01') & (data['Date'] < '2019-01-01')][['Date']]
    print(len(data) - len(predicted_period) - 60)
    df_test = data[len(data) - len(predicted_period) - 60:]
    train_cols = ["RSI", "ATR", "Volume", "Returns"]
    x = df_train[train_cols].values
    print(x)
    
    #scaling
    min_max_scaler = MinMaxScaler(feature_range = (0, 1))
    x_train = min_max_scaler.fit_transform(x)
    x_test = min_max_scaler.transform(df_test[train_cols])
    
    x_t, y_t = build_timeseries(x_train, 1)
    print("Training Size", x_t.shape, y_t.shape)
    
    x_t_test, y_t_test = build_timeseries(x_test, 1)
    print("Test Size", x_t_test.shape, y_t_test.shape)
    
    x_left, x_val = train_test_split(x_t, test_size=0.2, shuffle=False)
    y_left, y_val = train_test_split(y_t, test_size=0.2, shuffle=False)
    
    tuner = kt.BayesianOptimization(
        model_builder,
        objective='val_loss',
        max_trials=5)
    tuner.search(x_t, y_t, epochs=5, validation_data=(x_val,y_val))
    lstm_model  = tuner.get_best_models()[0]  
    print(ticker,lstm_model.summary())
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    #Model Training
    history_lstm = lstm_model.fit(x_t, y_t, epochs=params["EPOCHS"], verbose=1, batch_size=BATCH_SIZE, callbacks=[callback],
                                shuffle=False)
    y_pred_lstm = lstm_model.predict(x_t_test, batch_size=BATCH_SIZE)
    print(y_pred_lstm)
    y_pred_lstm = y_pred_lstm.flatten()
    print(y_pred_lstm)
    error_lstm = mean_squared_error(y_t_test, y_pred_lstm)
    mse[ticker] = error_lstm
    print(ticker,error_lstm)
    
    y_pred_lstm_org = (y_pred_lstm * min_max_scaler.data_range_[1]) + min_max_scaler.data_min_[1]   #Inverse Transform 
    predicted_returns = pd.Series(y_pred_lstm_org).to_frame(ticker)
    predicted_period = predicted_period.reset_index().drop(columns=['index'])
    result = predicted_returns.join(predicted_period)
    if  total_predicted_returns.empty:
        total_predicted_returns= result 
    else: 
        total_predicted_returns = pd.merge(result, total_predicted_returns, on='Date')

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     50.885506  0.518319 2013-01-03  352965200 -0.012703
2     45.305253  0.513950 2013-01-04  594333600 -0.028250
3     44.232810  0.513208 2013-01-07  484156400 -0.005900
4     44.872080  0.503693 2013-01-08  458707200  0.002688
5     41.863144  0.490725 2013-01-09  407604400 -0.015752
...         ...       ...        ...        ...       ...
1505  22.983638  1.395621 2018-12-24  148676800 -0.026215
1506  36.492605  1.483613 2018-12-26  234330000  0.068053
1507  35.825023  1.497283 2018-12-27  212468400 -0.006511
1508  35.924070  1.461227 2018-12-28  169165600  0.000512
1509  37.872294  1.412747 2018-12-31  140014000  0.009619

[1509 rows x 5 columns]
1198
[[ 5.08855061e+01  5.18319294e-01  3.52965200e+08 -1.27027104e-02]
 [ 4.53052532e+01  5.13949615e-01  5.94333600e+08 -2.82499616e-02]
 [ 4.42328105e+01  5.13208253e-01  4.84156400e+08 -5.89961289e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

AAPL 0.4132395671727298
[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     50.596832  0.513319 2013-01-03  48294400 -0.013487
2     45.127571  0.520225 2013-01-04  52521100 -0.018893
3     44.618429  0.500209 2013-01-07  37110400 -0.001872
4     43.150168  0.488051 2013-01-08  44703100 -0.005259
5     45.229713  0.467476 2013-01-09  49047900  0.005634
...         ...       ...        ...       ...       ...
1505  29.476148  3.722587 2018-12-24  43935200 -0.042635
1506  43.112585  3.937402 2018-12-26  51634800  0.066078
1507  44.232308  3.998302 2018-12-27  49498500  0.006146
1508  43.069064  3.919138 2018-12-28  38196300 -0.007838
1509  45.379682  3.782771 2018-12-31  33173800  0.011685

[1509 rows x 5 columns]
1198
[[ 5.05968318e+01  5.13319424e-01  4.82944000e+07 -1.34866373e-02]
 [ 4.51275712e+01  5.20225223e-01  5.25211000e+07 -1.88929878e-02]
 [ 4.46184291e+01  5.00209120e-01  3.71104000e+07 -1.871506

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     63.806858  0.303167 2013-01-03   93075567  0.000581
2     69.709819  0.313179 2013-01-04  110954331  0.019568
3     67.057713  0.306465 2013-01-07   66476239 -0.004373
4     65.842868  0.305692 2013-01-08   67295297 -0.001975
5     67.923125  0.301203 2013-01-09   81291563  0.006552
...         ...       ...        ...        ...       ...
1505  34.556117  1.742417 2018-12-24   31806000 -0.003395
1506  49.665784  1.845744 2018-12-26   47466000  0.062769
1507  50.525556  1.881370 2018-12-27   42196000  0.004243
1508  49.135022  1.827200 2018-12-28   28296000 -0.006535
1509  48.822206  1.800650 2018-12-31   29866000 -0.001418

[1509 rows x 5 columns]
1198
[[ 6.38068579e+01  3.03167180e-01  9.30755670e+07  5.80599965e-04]
 [ 6.97098194e+01  3.13179409e-01  1.10954331e+08  1.95676820e-02]
 [ 6.70577125e+01  3.06464969e-01  6.64762390e+07 -4.37280770e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 92)            35696     
                                                                 
 global_average_pooling1d (  (None, 92)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                5580      
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     63.806890  0.304608 2013-01-03   92635272  0.000581
2     69.709873  0.314668 2013-01-04  110429460  0.019568
3     67.057689  0.307922 2013-01-07   66161772 -0.004373
4     65.842906  0.307145 2013-01-08   66976956 -0.001975
5     67.923160  0.302634 2013-01-09   80907012  0.006552
...         ...       ...        ...        ...       ...
1505  34.590236  1.786591 2018-12-24   36360000 -0.006660
1506  49.279060  1.886763 2018-12-26   46318000  0.062189
1507  50.240917  1.917494 2018-12-27   45996000  0.004808
1508  49.008156  1.859923 2018-12-28   34398000 -0.005925
1509  48.652654  1.834036 2018-12-31   33110000 -0.001645

[1509 rows x 5 columns]
1198
[[ 6.38068900e+01  3.04608112e-01  9.26352720e+07  5.80592580e-04]
 [ 6.97098726e+01  3.14667962e-01  1.10429460e+08  1.95677297e-02]
 [ 6.70576891e+01  3.07921583e-01  6.61617720e+07 -4.37292695e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     58.842540  0.278285 2013-01-03   55018000  0.004537
2     59.455583  0.269658 2013-01-04   37484000  0.002589
3     66.845444  0.288182 2013-01-07   98200000  0.035295
4     64.037190  0.286919 2013-01-08   60214000 -0.007778
5     63.995427  0.281068 2013-01-09   45312000 -0.000113
...         ...       ...        ...        ...       ...
1505  29.222786  3.722038 2018-12-24  144400000 -0.024613
1506  42.165661  3.917606 2018-12-26  208236000  0.090254
1507  41.568493  3.918813 2018-12-27  194440000 -0.006315
1508  43.103510  3.869148 2018-12-28  176580000  0.011144
1509  45.363596  3.745423 2018-12-31  139090000  0.016074

[1509 rows x 5 columns]
1198
[[ 5.88425399e+01  2.78285219e-01  5.50180000e+07  4.53668633e-03]
 [ 5.94555828e+01  2.69657655e-01  3.74840000e+07  2.58877498e-03]
 [ 6.68454441e+01  2.88182060e-01  9.82000000e+07  3.52948721e-02]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 512)           1058816   
                                                                 
 global_average_pooling1d (  (None, 512)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                30780     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     60.423352  0.075814 2013-01-03  29888800  0.000786
2     67.742509  0.078970 2013-01-04  52496800  0.032460
3     57.399505  0.082258 2013-01-07  61073200 -0.029323
4     51.196695  0.084240 2013-01-08  46642400 -0.022170
5     45.859672  0.087508 2013-01-09  69502000 -0.022673
...         ...       ...        ...       ...       ...
1505  28.272512  2.321551 2018-12-24  46384000 -0.019404
1506  34.058154  2.310726 2018-12-26  69510000  0.046284
1507  33.135366  2.274245 2018-12-27  63704400 -0.014607
1508  35.551779  2.238228 2018-12-28  62872800  0.018730
1509  35.468279  2.157819 2018-12-31  46514000 -0.001123

[1509 rows x 5 columns]
1198
[[ 6.04233522e+01  7.58142446e-02  2.98888000e+07  7.85856890e-04]
 [ 6.77425091e+01  7.89703618e-02  5.24968000e+07  3.24602797e-02]
 [ 5.73995046e+01  8.22581931e-02  6.10732000e+07 -2.93229324e-02]
 ...
 [ 5.027526

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     57.820695  0.066655 2013-01-03   11130000 -0.016826
2     54.875638  0.066084 2013-01-04   10110000 -0.010699
3     54.391837  0.065650 2013-01-07    6630000 -0.001746
4     49.248294  0.067580 2013-01-08   19260000 -0.019407
5     48.946272  0.066514 2013-01-09   10470000 -0.001188
...         ...       ...        ...        ...       ...
1505  31.334964  0.996541 2018-12-24   83398500 -0.079305
1506  45.440901  1.081931 2018-12-26  122446500  0.098877
1507  42.397807  1.103078 2018-12-27  128626500 -0.031020
1508  48.954772  1.120049 2018-12-28  149085000  0.054598
1509  48.595460  1.106474 2018-12-31   94534500 -0.003210

[1509 rows x 5 columns]
1198
[[ 5.78206946e+01  6.66548773e-02  1.11300000e+07 -1.68260932e-02]
 [ 5.48756380e+01  6.60843107e-02  1.01100000e+07 -1.06985374e-02]
 [ 5.43918374e+01  6.56497130e-02  6.63000000e+06 -1.74568663e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     59.089676  1.047264 2013-01-03   63140600 -0.008248
2     63.705055  1.055316 2013-01-04   72715400  0.035029
3     66.424559  1.061365 2013-01-07   83781800  0.022689
4     63.624223  1.038411 2013-01-08   45871300 -0.012312
5     69.507821  1.074239 2013-01-09  104787700  0.051311
...         ...       ...        ...        ...       ...
1505  31.108940  5.769428 2018-12-24   22066000 -0.007148
1506  45.302163  6.084470 2018-12-26   39723400  0.078417
1507  45.706889  6.029865 2018-12-27   31202500  0.002531
1508  44.335349  5.864875 2018-12-28   22627600 -0.009861
1509  42.157669  5.780956 2018-12-31   24625300 -0.015968

[1509 rows x 5 columns]
1198
[[ 5.90896755e+01  1.04726384e+00  6.31406000e+07 -8.24819237e-03]
 [ 6.37050553e+01  1.05531641e+00  7.27154000e+07  3.50292230e-02]
 [ 6.64245590e+01  1.06136533e+00  8.37818000e+07  2.26891770e-02]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 392)           622496    
                                                                 
 global_average_pooling1d (  (None, 392)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                23580     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date   Volume   Returns
1     64.003149  0.599988 2013-01-03  1339800 -0.017466
2     66.209028  0.590703 2013-01-04  1457200  0.006167
3     66.740955  0.572081 2013-01-07  1432900  0.001489
4     59.434383  0.566218 2013-01-08  1892900 -0.010847
5     63.312393  0.580060 2013-01-09  1459500  0.009731
...         ...       ...        ...      ...       ...
1505  42.509934  0.791440 2018-12-24  1771100 -0.004695
1506  49.653455  0.822052 2018-12-26  2421200  0.021079
1507  45.870616  0.824048 2018-12-27  3242700 -0.012938
1508  48.802967  0.811616 2018-12-28  2190500  0.009050
1509  49.123903  0.793644 2018-12-31  1719900  0.000974

[1509 rows x 5 columns]
1198
[[ 6.40031489e+01  5.99987739e-01  1.33980000e+06 -1.74659142e-02]
 [ 6.62090282e+01  5.90702987e-01  1.45720000e+06  6.16651659e-03]
 [ 6.67409549e+01  5.72081204e-01  1.43290000e+06  1.48901530e-03]
 ...
 [ 6.44897567e+01  4.69

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 272)           301376    
                                                                 
 global_average_pooling1d (  (None, 272)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                16380     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     56.656129  0.835728 2013-01-03   7448100  0.004232
2     67.227326  0.931748 2013-01-04  13587200  0.036339
3     66.562325  0.928766 2013-01-07   6989100 -0.001359
4     68.435921  0.915283 2013-01-08   5246100  0.007546
5     72.991097  0.934191 2013-01-09   7267200  0.020792
...         ...       ...        ...       ...       ...
1505  37.523475  2.825029 2018-12-24   3284000 -0.024704
1506  48.992265  2.956098 2018-12-26   3792400  0.039851
1507  52.857546  3.042805 2018-12-27   4101600  0.016073
1508  55.500462  3.004033 2018-12-28   3984000  0.011537
1509  58.413726  2.907317 2018-12-31   2731000  0.013222

[1509 rows x 5 columns]
1198
[[ 5.66561291e+01  8.35728457e-01  7.44810000e+06  4.23244275e-03]
 [ 6.72273265e+01  9.31747875e-01  1.35872000e+07  3.63391519e-02]
 [ 6.65623249e+01  9.28766112e-01  6.98910000e+06 -1.35864120e-03]
 ...
 [ 4.818439

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     75.597387  0.315118 2013-01-03  13148600 -0.000552
2     71.156360  0.306895 2013-01-04   7464200 -0.007212
3     63.164586  0.298545 2013-01-07   9429900 -0.014583
4     58.788602  0.292935 2013-01-08   8112900 -0.009080
5     58.788602  0.309868 2013-01-09  12977400  0.000000
...         ...       ...        ...       ...       ...
1505  37.537035  0.908531 2018-12-24   6288500 -0.011831
1506  49.031579  0.949350 2018-12-26  10063400  0.040810
1507  49.168606  0.941540 2018-12-27   8688600  0.000544
1508  51.687011  0.938573 2018-12-28   7369000  0.009740
1509  49.983181  0.930103 2018-12-31   4600600 -0.006212

[1509 rows x 5 columns]
1198
[[ 7.55973867e+01  3.15117616e-01  1.31486000e+07 -5.52437490e-04]
 [ 7.11563600e+01  3.06894984e-01  7.46420000e+06 -7.21227695e-03]
 [ 6.31645856e+01  2.98545380e-01  9.42990000e+06 -1.45825059e-02]
 ...
 [ 3.997623

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     68.339799  0.595815 2013-01-03  14937200  0.000772
2     70.518633  0.596293 2013-01-04  10376000  0.008134
3     72.327521  0.589415 2013-01-07  10242400  0.007119
4     74.535760  0.589278 2013-01-08  11800400  0.009267
5     77.703212  0.604151 2013-01-09  17552800  0.015134
...         ...       ...        ...       ...       ...
1505  29.106984  4.241238 2018-12-24   8617700 -0.020571
1506  44.326948  4.546150 2018-12-26  13499500  0.067497
1507  46.898034  4.613568 2018-12-27  10883000  0.013576
1508  45.536634  4.566884 2018-12-28   7381300 -0.008139
1509  47.082701  4.398535 2018-12-31   7976000  0.007608

[1509 rows x 5 columns]
1198
[[ 6.83397988e+01  5.95815305e-01  1.49372000e+07  7.71898938e-04]
 [ 7.05186335e+01  5.96292849e-01  1.03760000e+07  8.13441023e-03]
 [ 7.23275210e+01  5.89414788e-01  1.02424000e+07  7.11856960e-03]
 ...
 [ 5.963915

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     36.930554  0.922022 2013-01-03  14413200 -0.047883
2     37.696086  0.909020 2013-01-04  10458000  0.001922
3     37.696086  0.899805 2013-01-07   7804500  0.000000
4     34.358943  0.898390 2013-01-08   8196200 -0.013335
5     42.116727  0.912791 2013-01-09   5154300  0.018696
...         ...       ...        ...       ...       ...
1505  24.997998  7.370625 2018-12-24   3091000 -0.022917
1506  36.801839  7.669866 2018-12-26   4159300  0.043720
1507  39.387366  7.888447 2018-12-27   4295800  0.010709
1508  39.661331  7.680700 2018-12-28   3312700  0.001097
1509  42.639502  7.420650 2018-12-31   3123200  0.011628

[1509 rows x 5 columns]
1198
[[ 3.69305541e+01  9.22022155e-01  1.44132000e+07 -4.78830457e-02]
 [ 3.76960860e+01  9.09020420e-01  1.04580000e+07  1.92162726e-03]
 [ 3.76960860e+01  8.99804861e-01  7.80450000e+06  0.00000000e+00]
 ...
 [ 5.411686

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 512)           1058816   
                                                                 
 global_average_pooling1d (  (None, 512)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                30780     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     52.970481  1.204402 2013-01-03  13268200 -0.001805
2     54.794415  1.169802 2013-01-04  11427900  0.004619
3     49.590835  1.151959 2013-01-07  11799800 -0.011646
4     52.201376  1.154676 2013-01-08  14226400  0.006236
5     50.461714  1.128628 2013-01-09  10892200 -0.003850
...         ...       ...        ...       ...       ...
1505  20.097195  2.067170 2018-12-24  14262800 -0.039068
1506  33.197904  2.205944 2018-12-26  24887700  0.046673
1507  34.309628  2.252662 2018-12-27  22077000  0.004361
1508  32.800779  2.217472 2018-12-28  19710600 -0.011232
1509  32.883366  2.165510 2018-12-31  15807000  0.000293

[1509 rows x 5 columns]
1198
[[ 5.29704810e+01  1.20440224e+00  1.32682000e+07 -1.80528488e-03]
 [ 5.47944151e+01  1.16980162e+00  1.14279000e+07  4.61943771e-03]
 [ 4.95908354e+01  1.15195852e+00  1.17998000e+07 -1.16460577e-02]
 ...
 [ 6.218277

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 392)           622496    
                                                                 
 global_average_pooling1d (  (None, 392)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                23580     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     67.421316  0.756418 2013-01-03  24227700 -0.002018
2     71.680925  0.773103 2013-01-04  24487700  0.017570
3     71.931053  0.751453 2013-01-07  24456900  0.001101
4     72.403548  0.736349 2013-01-08  19624200  0.001980
5     71.968487  0.759467 2013-01-09  25920600 -0.000660
...         ...       ...        ...       ...       ...
1505  20.814913  2.744690 2018-12-24  17009300 -0.021792
1506  34.730753  2.895069 2018-12-26  22542900  0.040622
1507  38.045717  2.945421 2018-12-27  20304700  0.011192
1508  37.645381  2.869320 2018-12-28  17963300 -0.002166
1509  40.195052  2.810082 2018-12-31  13237200  0.008126

[1509 rows x 5 columns]
1198
[[ 6.74213162e+01  7.56418307e-01  2.42277000e+07 -2.01794426e-03]
 [ 7.16809254e+01  7.73102834e-01  2.44877000e+07  1.75700690e-02]
 [ 7.19310528e+01  7.51452719e-01  2.44569000e+07  1.10149659e-03]
 ...
 [ 6.267344

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     45.058527  0.908669 2013-01-03   8910100 -0.006375
2     46.929911  0.903765 2013-01-04   6438000  0.003772
3     42.932481  0.895639 2013-01-07   6201400 -0.009603
4     44.400611  0.880236 2013-01-08   5866900  0.002774
5     44.271437  0.852362 2013-01-09   5055200 -0.000292
...         ...       ...        ...       ...       ...
1505  22.049050  1.980552 2018-12-24   6110300 -0.015149
1506  42.246710  2.167655 2018-12-26  10028300  0.052103
1507  46.112326  2.239251 2018-12-27   9881500  0.012967
1508  47.833182  2.213590 2018-12-28   9874000  0.005879
1509  51.015116  2.145477 2018-12-31   7005800  0.011011

[1509 rows x 5 columns]
1198
[[ 4.50585274e+01  9.08669495e-01  8.91010000e+06 -6.37516438e-03]
 [ 4.69299109e+01  9.03764814e-01  6.43800000e+06  3.77182159e-03]
 [ 4.29324812e+01  8.95638821e-01  6.20140000e+06 -9.60296427e-03]
 ...
 [ 6.943379

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 32)            4736      
                                                                 
 global_average_pooling1d (  (None, 32)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                1980      
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date   Volume   Returns
1     63.715073  0.194377 2013-01-03  2462000 -0.002898
2     66.176254  0.189708 2013-01-04  1611000  0.005907
3     67.554744  0.192300 2013-01-07  2802000  0.003420
4     71.192639  0.191636 2013-01-08  4150000  0.009775
5     71.936511  0.189733 2013-01-09  2535000  0.002133
...         ...       ...        ...      ...       ...
1505  41.594219  0.458917 2018-12-24  1744400 -0.011077
1506  49.161106  0.478637 2018-12-26  2354600  0.024254
1507  52.361377  0.479448 2018-12-27  2486000  0.011472
1508  53.806691  0.470202 2018-12-28  2713600  0.005250
1509  55.268182  0.450545 2018-12-31  1450400  0.005223

[1509 rows x 5 columns]
1198
[[ 6.37150733e+01  1.94377381e-01  2.46200000e+06 -2.89752866e-03]
 [ 6.61762538e+01  1.89707547e-01  1.61100000e+06  5.90724238e-03]
 [ 6.75547445e+01  1.92299853e-01  2.80200000e+06  3.42024300e-03]
 ...
 [ 6.35602110e+01  3.29

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 272)           301376    
                                                                 
 global_average_pooling1d (  (None, 272)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                16380     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     56.994588  0.646496 2013-01-03   9598300 -0.001413
2     64.242990  0.671032 2013-01-04  11631800  0.011386
3     62.153790  0.647387 2013-01-07   7548800 -0.002098
4     62.241926  0.629717 2013-01-08   9825300  0.000140
5     65.047577  0.616165 2013-01-09   7672800  0.004471
...         ...       ...        ...       ...       ...
1505  22.357910  3.818837 2018-12-24   7531900 -0.041851
1506  32.109660  3.885349 2018-12-26   9253000  0.031018
1507  33.730999  3.917824 2018-12-27   9918700  0.005509
1508  33.558349  3.780837 2018-12-28   6537200 -0.001100
1509  37.909058  3.673635 2018-12-31   7409900  0.013889

[1509 rows x 5 columns]
1198
[[ 5.69945877e+01  6.46495924e-01  9.59830000e+06 -1.41273000e-03]
 [ 6.42429899e+01  6.71032322e-01  1.16318000e+07  1.13855158e-02]
 [ 6.21537904e+01  6.47386894e-01  7.54880000e+06 -2.09842788e-03]
 ...
 [ 5.171513

C:\Users\user\AppData\Local\Temp\ipykernel_23460\465918227.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 92)            35696     
                                                                 
 global_average_pooling1d (  (None, 92)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                5580      
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

In [59]:
total_predicted_returns

JNJ       Date       NVO       WMT       JPM       XOM      UNH  \
0    1.274866 2018-01-02  0.358531  1.163523  1.259298  1.203410  2.03171   
1    1.275352 2018-01-03  0.358587  1.165196  1.259418  1.203309  2.03171   
2    1.275841 2018-01-04  0.358572  1.166685  1.259448  1.203418  2.03171   
3    1.276590 2018-01-05  0.358574  1.167246  1.259383  1.203410  2.03171   
4    1.277604 2018-01-08  0.358593  1.166942  1.258220  1.203400  2.03171   
..        ...        ...       ...       ...       ...       ...      ...   
246  1.369481 2018-12-24  0.359139  1.208380  1.254396  1.204084  2.03171   
247  1.373728 2018-12-26  0.359121  1.210717  1.252049  1.204049  2.03171   
248  1.377628 2018-12-27  0.359171  1.213619  1.255085  1.204190  2.03171   
249  1.380723 2018-12-28  0.359253  1.216321  1.254461  1.204152  2.03171   
250  1.383748 2018-12-31  0.359190  1.218289  1.254645  1.204050  2.03171   

            V       TSM       LLY      HSBC      META      TSLA      NVDA  \
0    1.141620  0.507688  1.366064  0.493111  2.208042  0.540090  0.364042   
1    1.141765  0.507748  1.366184  0.492839  2.208081  0.539703  0.364003   
2    1.141832  0.508129  1.366255  0.492638  2.208094  0.542940  0.363995   
3    1.142026  0.508063  1.366424  0.492708  2.208059  0.538577  0.364034   
4    1.141910  0.508152  1.366529  0.492614  2.207635  0.539410  0.363993   
..        ...       ...       ...       ...       ...       ...       ...   
246  1.141326  0.505509  1.368345  0.508687  2.215090  0.551294  0.364275   
247  1.141371  0.504897  1.368076  0.508736  2.216480  0.555004  0.364307   
248  1.141156  0.505430  1.367578  0.509059  2.216615  0.548919  0.364326   
249  1.141121  0.504418  1.367179  0.509189  2.216569  0.556297  0.364336   
250  1.141005  0.504968  1.367136  0.509691  2.216103  0.555784  0.364337   

         AMZN     GOOGL      GOOG      MSFT      AAPL  
0    0.571188  0.579567  0.537375  0.945141  0.506326  
1    0.571188  0.579567  0.537229  0.945242  0.505884  
2    0.571188  0.579567  0.537173  0.945296  0.505599  
3    0.571188  0.579567  0.537259  0.945137  0.505937  
4    0.571188  0.579567  0.537431  0.945045  0.505391  
..        ...       ...       ...       ...       ...  
246  0.571188  0.579567  0.666979  0.947111  0.512949  
247  0.571188  0.579567  0.668048  0.947098  0.512787  
248  0.571188  0.579567  0.669074  0.947408  0.512722  
249  0.571188  0.579567  0.669989  0.947191  0.512639  
250  0.571188  0.579567  0.670146  0.947067  0.512486  

[251 rows x 19 columns]