In [1]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import yfinance as yf
import numpy as np
from functools import reduce

## Stock Feature Selection: Adj Close, Volume, RSI, ATR

In [35]:
tickers = pd.read_csv('tickers.csv')
tickers.sort_values(by='Market Cap', ascending=False, inplace=True)
top18_tickers = tickers[:20]
top18_tickers.reset_index(inplace=True)
top18_tickers = top18_tickers.drop([7,8])
stocks = top18_tickers['Symbol'].to_list()
start_date = '2013-01-01'
end_date = '2019-01-01'
data = yf.download("AAPL", start=start_date, end=end_date)
data = data.reset_index()
dates = data['Date']

[*********************100%%**********************]  1 of 1 completed


In [44]:
def get_log_returns(list_of_stocks_tickers, start_date, end_date, interval='1d'):
    stocks = list()
    for ticker in list_of_stocks_tickers:
        data = yf.download(ticker, start=start_date, end=end_date, interval=interval)
        data = {ticker: np.log(data['Adj Close']) - np.log(data['Adj Close'].shift(1))}
        log_return = pd.DataFrame(data=data)
        stocks.append(log_return)
    all_stocks = reduce(lambda df1, df2: pd.merge(df1, df2, on='Date'), stocks)
    all_stocks['Date'] = log_return.index
    return all_stocks

In [45]:
stocks

['AAPL',
 'MSFT',
 'GOOG',
 'GOOGL',
 'AMZN',
 'NVDA',
 'TSLA',
 'META',
 'HSBC',
 'LLY',
 'TSM',
 'V',
 'UNH',
 'XOM',
 'JPM',
 'WMT',
 'NVO',
 'JNJ']

In [46]:
returns = get_log_returns(stocks, start_date, end_date)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%*******

In [63]:
returns.to_csv("base_returns.csv")

In [48]:
def calculate_rsi(prices, n=14):
    deltas = np.diff(prices)
    seed = deltas[:n+1]
    up = seed[seed >= 0].sum()/n
    down = -seed[seed < 0].sum()/n
    rs = up/down
    rsi = np.zeros_like(prices)
    rsi[:n] = 100. - 100./(1.+rs)

    for i in range(n, len(prices)):
        delta = deltas[i-1]  # The diff is 1 shorter

        if delta > 0:
            upval = delta
            downval = 0.
        else:
            upval = 0.
            downval = -delta

        up = (up*(n-1) + upval)/n
        down = (down*(n-1) + downval)/n

        rs = up/down
        rsi[i] = 100. - 100./(1.+rs)

    return rsi

In [49]:
def calculate_rsi(data, period=14):
    # Calculate price differences
    price_diff = np.diff(data)
    
    # Calculate initial seed values
    seed = price_diff[:period + 1]
    positive_seed = seed[seed >= 0].sum()
    negative_seed = -seed[seed < 0].sum()
    
    # Calculate initial RS and RSI
    initial_rs = positive_seed / negative_seed
    initial_rsi = 100 - 100 / (1 + initial_rs)
    
    # Initialize up and down values
    up = positive_seed / period
    down = negative_seed / period
    
    # Initialize RSI array
    rsi = np.zeros_like(data)
    rsi[:period] = initial_rsi

    for i in range(period, len(data)):
        # Calculate delta for the current period
        delta = price_diff[i - 1]
        
        if delta > 0:
            upval = delta
            downval = 0.
        else:
            upval = 0.
            downval = -delta
        
        # Update up and down values
        up = (up * (period - 1) + upval) / period
        down = (down * (period - 1) + downval) / period
        
        # Calculate RS and RSI for the current period
        current_rs = up / down
        rsi[i] = 100 - 100 / (1 + current_rs)

    return rsi


In [50]:
def calculate_atr(data, period=14):
    data = np.array(data)
    
    high = data[:, 0]
    low = data[:, 1]
    close = data[:, 2]
    
    tr = np.maximum(high - low, np.abs(high - np.roll(close, 1)), np.abs(low - np.roll(close, 1)))
    
    atr = np.zeros_like(tr)
    atr[period] = np.mean(tr[:period])
    
    for i in range(period + 1, len(tr)):
        atr[i] = ((period - 1) * atr[i - 1] + tr[i]) / period
    
    return atr

## Model Param

In [51]:
params = {
    "BATCH_SIZE": 50,
    "EPOCHS": 10,
    "LR": 0.00010000,
    "TIME_STEPS": 60
    }

TIME_STEPS = params['TIME_STEPS']
BATCH_SIZE = params['BATCH_SIZE']


def build_timeseries(mat, y_col_index):
    
    dim_0 = mat.shape[0] - TIME_STEPS
    dim_1 = mat.shape[1]

    x = np.zeros((dim_0, TIME_STEPS, dim_1))
    y = np.zeros((dim_0,))

    print("Length of inputs", dim_0)

    for i in range(dim_0):
        x[i] = mat[i:TIME_STEPS+i]
        y[i] = mat[TIME_STEPS+i, y_col_index]

    print("length of time-series - inputs", x.shape)
    print("length of time-series - outputs", y.shape)


    return x, y
     

## Model

In [52]:
pip install keras_tuner

Note: you may need to restart the kernel to use updated packages.


In [53]:
from sklearn.preprocessing import MinMaxScaler
import keras
import tensorflow as tf
from keras.models import Model
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM, Input, Activation,concatenate, Attention, Bidirectional,GlobalAveragePooling1D
from keras import optimizers
from keras.preprocessing.sequence import TimeseriesGenerator
from keras.layers import LeakyReLU
import matplotlib.pyplot as plt
import keras_tuner as kt
plt.style.use('fivethirtyeight')
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [57]:
def model_builder(hyperparameters):
    lstm_model = Sequential()
    
    hyperparameters_units = hyperparameters.Int('units', min_value=50, max_value=100, step=TIME_STEPS)
    lstm_model.add(LSTM(units=hyperparameters_units, 
                        input_shape=(x_t.shape[1], x_t.shape[2]), 
                        return_sequences=True,
                        kernel_initializer='he_normal'))
    lstm_model.add(GlobalAveragePooling1D())
    lstm_model.add(Dense(60,activation='relu'))
    lstm_model.add(Dense(20,activation='relu'))
    lstm_model.add(Dropout(0.05))
    lstm_model.add(Dense(1, activation='linear'))
    
    hyperparameters_learning_rate = hyperparameters.Choice('learning_rate', values=[0.01, 0.05, 0.1])
    
    lstm_model.compile(loss='mean_squared_error', optimizer=keras.optimizers.Adam(learning_rate=hyperparameters_learning_rate))
    
    return lstm_model

In [60]:
mse = {}
total_predicted_returns = pd.DataFrame()
for ticker in stocks:
    df = yf.download(ticker, start=start_date, end=end_date, interval='1d')
    df['RSI'] = calculate_rsi(df['Adj Close'])
    df['ATR'] = calculate_atr(df[['High', 'Low', 'Close']])
    stock_returns = returns[[ticker]].reset_index()
    stock_returns['Date'] = stock_returns['Date'].apply(lambda x: x.strftime('%Y-%m-%d'))
    df.reset_index(inplace=True)
    df_stock = df[['RSI', 'ATR', 'Date', 'Volume']]
    stock_returns.Date = pd.to_datetime(stock_returns.Date)
    df_stock.Date = pd.to_datetime(df_stock.Date)
    data = pd.merge(df_stock[['RSI', 'ATR', 'Date', 'Volume']],  stock_returns , on='Date')[1:].rename(columns={ticker : 'Returns'})
    print(data)
    # Split the data we try by years first
    data = data[data['Date'] < '2019-01-01']
    df_train = data[data['Date'] < '2018-01-01']
    predicted_period = data[(data['Date'] >= '2018-01-01') & (data['Date'] < '2019-01-01')][['Date']]
    print(len(data) - len(predicted_period) - 60)
    df_test = data[len(data) - len(predicted_period) - 60:]
    train_cols = ["RSI", "ATR", "Volume", "Returns"]
    x = df_train[train_cols].values
    print(x)
    
    #scaling
    min_max_scaler = MinMaxScaler(feature_range = (0, 1))
    x_train = min_max_scaler.fit_transform(x)
    x_test = min_max_scaler.transform(df_test[train_cols])
    
    x_t, y_t = build_timeseries(x_train, 1)
    print("Training Size", x_t.shape, y_t.shape)
    
    x_t_test, y_t_test = build_timeseries(x_test, 1)
    print("Test Size", x_t_test.shape, y_t_test.shape)
    
    x_left, x_val = train_test_split(x_t, test_size=0.2, shuffle=False)
    y_left, y_val = train_test_split(y_t, test_size=0.2, shuffle=False)
    
    tuner = kt.BayesianOptimization(
        model_builder,
        objective='val_loss',
        max_trials=5)
    tuner.search(x_t, y_t, epochs=5, validation_data=(x_val,y_val))
    lstm_model  = tuner.get_best_models()[0]  
    print(ticker,lstm_model.summary())
    callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
    #Model Training
    history_lstm = lstm_model.fit(x_t, y_t, epochs=params["EPOCHS"], verbose=1, batch_size=BATCH_SIZE, callbacks=[callback],
                                shuffle=False)
    y_pred_lstm = lstm_model.predict(x_t_test, batch_size=BATCH_SIZE)
    print(y_pred_lstm)
    y_pred_lstm = y_pred_lstm.flatten()
    print(y_pred_lstm)
    error_lstm = mean_squared_error(y_t_test, y_pred_lstm)
    mse[ticker] = error_lstm
    print(ticker,error_lstm)
    
    y_pred_lstm_org = (y_pred_lstm * min_max_scaler.data_range_[1]) + min_max_scaler.data_min_[1]   #Inverse Transform 
    predicted_returns = pd.Series(y_pred_lstm_org).to_frame(ticker)
    predicted_period = predicted_period.reset_index().drop(columns=['index'])
    result = predicted_returns.join(predicted_period)
    if  total_predicted_returns.empty:
        total_predicted_returns= result 
    else: 
        total_predicted_returns = pd.merge(result, total_predicted_returns, on='Date')

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     23.009684  0.000000 2013-01-03  352965200 -0.012703
2     23.009684  0.000000 2013-01-04  594333600 -0.028250
3     23.009684  0.000000 2013-01-07  484156400 -0.005900
4     23.009684  0.000000 2013-01-08  458707200  0.002688
5     23.009684  0.000000 2013-01-09  407604400 -0.015752
...         ...       ...        ...        ...       ...
1505  22.983592  1.395621 2018-12-24  148676800 -0.026215
1506  36.492563  1.483613 2018-12-26  234330000  0.068053
1507  35.825001  1.497283 2018-12-27  212468400 -0.006511
1508  35.924049  1.461227 2018-12-28  169165600  0.000512
1509  37.872277  1.412747 2018-12-31  140014000  0.009619

[1509 rows x 5 columns]
1198
[[ 2.30096839e+01  0.00000000e+00  3.52965200e+08 -1.27027104e-02]
 [ 2.30096839e+01  0.00000000e+00  5.94333600e+08 -2.82499616e-02]
 [ 2.30096839e+01  0.00000000e+00  4.84156400e+08 -5.89961289e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     50.157734  0.000000 2013-01-03  48294400 -0.013487
2     50.157734  0.000000 2013-01-04  52521100 -0.018893
3     50.157734  0.000000 2013-01-07  37110400 -0.001872
4     50.157734  0.000000 2013-01-08  44703100 -0.005259
5     50.157734  0.000000 2013-01-09  49047900  0.005634
...         ...       ...        ...       ...       ...
1505  29.476164  3.722587 2018-12-24  43935200 -0.042635
1506  43.112583  3.937402 2018-12-26  51634800  0.066078
1507  44.232346  3.998302 2018-12-27  49498500  0.006146
1508  43.069046  3.919138 2018-12-28  38196300 -0.007838
1509  45.379688  3.782771 2018-12-31  33173800  0.011685

[1509 rows x 5 columns]
1198
[[ 5.01577338e+01  0.00000000e+00  4.82944000e+07 -1.34866373e-02]
 [ 5.01577338e+01  0.00000000e+00  5.25211000e+07 -1.88929878e-02]
 [ 5.01577338e+01  0.00000000e+00  3.71104000e+07 -1.87150602e-03]
 ...
 [ 5.882161

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 392)           622496    
                                                                 
 global_average_pooling1d (  (None, 392)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                23580     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     62.806101  0.000000 2013-01-03   93075567  0.000581
2     62.806101  0.000000 2013-01-04  110954331  0.019568
3     62.806101  0.000000 2013-01-07   66476239 -0.004373
4     62.806101  0.000000 2013-01-08   67295297 -0.001975
5     62.806101  0.000000 2013-01-09   81291563  0.006552
...         ...       ...        ...        ...       ...
1505  34.556117  1.742417 2018-12-24   31806000 -0.003395
1506  49.665784  1.845744 2018-12-26   47466000  0.062769
1507  50.525556  1.881370 2018-12-27   42196000  0.004243
1508  49.135022  1.827200 2018-12-28   28296000 -0.006535
1509  48.822206  1.800650 2018-12-31   29866000 -0.001418

[1509 rows x 5 columns]
1198
[[ 6.28061011e+01  0.00000000e+00  9.30755670e+07  5.80599965e-04]
 [ 6.28061011e+01  0.00000000e+00  1.10954331e+08  1.95676820e-02]
 [ 6.28061011e+01  0.00000000e+00  6.64762390e+07 -4.37280770e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     62.806087  0.000000 2013-01-03   92635272  0.000581
2     62.806087  0.000000 2013-01-04  110429460  0.019568
3     62.806087  0.000000 2013-01-07   66161772 -0.004373
4     62.806087  0.000000 2013-01-08   66976956 -0.001975
5     62.806087  0.000000 2013-01-09   80907012  0.006552
...         ...       ...        ...        ...       ...
1505  34.590236  1.786591 2018-12-24   36360000 -0.006660
1506  49.279060  1.886763 2018-12-26   46318000  0.062189
1507  50.240917  1.917494 2018-12-27   45996000  0.004808
1508  49.008156  1.859923 2018-12-28   34398000 -0.005925
1509  48.652654  1.834036 2018-12-31   33110000 -0.001645

[1509 rows x 5 columns]
1198
[[ 6.28060868e+01  0.00000000e+00  9.26352720e+07  5.80592580e-04]
 [ 6.28060868e+01  0.00000000e+00  1.10429460e+08  1.95677297e-02]
 [ 6.28060868e+01  0.00000000e+00  6.61617720e+07 -4.37292695e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 272)           301376    
                                                                 
 global_average_pooling1d (  (None, 272)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                16380     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     71.244403  0.000000 2013-01-03   55018000  0.004537
2     71.244403  0.000000 2013-01-04   37484000  0.002589
3     71.244403  0.000000 2013-01-07   98200000  0.035295
4     71.244403  0.000000 2013-01-08   60214000 -0.007778
5     71.244403  0.000000 2013-01-09   45312000 -0.000113
...         ...       ...        ...        ...       ...
1505  29.222786  3.722038 2018-12-24  144400000 -0.024613
1506  42.165661  3.917606 2018-12-26  208236000  0.090254
1507  41.568493  3.918813 2018-12-27  194440000 -0.006315
1508  43.103510  3.869148 2018-12-28  176580000  0.011144
1509  45.363596  3.745423 2018-12-31  139090000  0.016074

[1509 rows x 5 columns]
1198
[[ 7.12444030e+01  0.00000000e+00  5.50180000e+07  4.53668633e-03]
 [ 7.12444030e+01  0.00000000e+00  3.74840000e+07  2.58877498e-03]
 [ 7.12444030e+01  0.00000000e+00  9.82000000e+07  3.52948721e-02]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 512)           1058816   
                                                                 
 global_average_pooling1d (  (None, 512)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                30780     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

AMZN 0.07669444407615947
[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     37.558534  0.000000 2013-01-03  29888800  0.000786
2     37.558534  0.000000 2013-01-04  52496800  0.032460
3     37.558534  0.000000 2013-01-07  61073200 -0.029323
4     37.558534  0.000000 2013-01-08  46642400 -0.022170
5     37.558534  0.000000 2013-01-09  69502000 -0.022673
...         ...       ...        ...       ...       ...
1505  28.272483  2.321551 2018-12-24  46384000 -0.019404
1506  34.058136  2.310726 2018-12-26  69510000  0.046284
1507  33.135340  2.274245 2018-12-27  63704400 -0.014607
1508  35.551728  2.238228 2018-12-28  62872800  0.018730
1509  35.468262  2.157819 2018-12-31  46514000 -0.001123

[1509 rows x 5 columns]
1198
[[ 3.75585343e+01  0.00000000e+00  2.98888000e+07  7.85856890e-04]
 [ 3.75585343e+01  0.00000000e+00  5.24968000e+07  3.24602797e-02]
 [ 3.75585343e+01  0.00000000e+00  6.10732000e+07 -2.93229

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 272)           301376    
                                                                 
 global_average_pooling1d (  (None, 272)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                16380     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     62.480921  0.000000 2013-01-03   11130000 -0.016826
2     62.480921  0.000000 2013-01-04   10110000 -0.010699
3     62.480921  0.000000 2013-01-07    6630000 -0.001746
4     62.480921  0.000000 2013-01-08   19260000 -0.019407
5     62.480921  0.000000 2013-01-09   10470000 -0.001188
...         ...       ...        ...        ...       ...
1505  31.334964  0.996541 2018-12-24   83398500 -0.079305
1506  45.440901  1.081931 2018-12-26  122446500  0.098877
1507  42.397807  1.103078 2018-12-27  128626500 -0.031020
1508  48.954772  1.120049 2018-12-28  149085000  0.054598
1509  48.595460  1.106474 2018-12-31   94534500 -0.003210

[1509 rows x 5 columns]
1198
[[ 6.24809206e+01  0.00000000e+00  1.11300000e+07 -1.68260932e-02]
 [ 6.24809206e+01  0.00000000e+00  1.01100000e+07 -1.06985374e-02]
 [ 6.24809206e+01  0.00000000e+00  6.63000000e+06 -1.74568663e-03]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 32)            4736      
                                                                 
 global_average_pooling1d (  (None, 32)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                1980      
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date     Volume   Returns
1     67.187505  0.000000 2013-01-03   63140600 -0.008248
2     67.187505  0.000000 2013-01-04   72715400  0.035029
3     67.187505  0.000000 2013-01-07   83781800  0.022689
4     67.187505  0.000000 2013-01-08   45871300 -0.012312
5     67.187505  0.000000 2013-01-09  104787700  0.051311
...         ...       ...        ...        ...       ...
1505  31.108940  5.769428 2018-12-24   22066000 -0.007148
1506  45.302163  6.084470 2018-12-26   39723400  0.078417
1507  45.706889  6.029865 2018-12-27   31202500  0.002531
1508  44.335349  5.864875 2018-12-28   22627600 -0.009861
1509  42.157669  5.780956 2018-12-31   24625300 -0.015968

[1509 rows x 5 columns]
1198
[[ 6.71875050e+01  0.00000000e+00  6.31406000e+07 -8.24819237e-03]
 [ 6.71875050e+01  0.00000000e+00  7.27154000e+07  3.50292230e-02]
 [ 6.71875050e+01  0.00000000e+00  8.37818000e+07  2.26891770e-02]
 ...

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date   Volume   Returns
1     61.971897  0.000000 2013-01-03  1339800 -0.017466
2     61.971897  0.000000 2013-01-04  1457200  0.006167
3     61.971897  0.000000 2013-01-07  1432900  0.001489
4     61.971897  0.000000 2013-01-08  1892900 -0.010847
5     61.971897  0.000000 2013-01-09  1459500  0.009731
...         ...       ...        ...      ...       ...
1505  42.509944  0.791440 2018-12-24  1771100 -0.004695
1506  49.653444  0.822052 2018-12-26  2421200  0.021079
1507  45.870627  0.824048 2018-12-27  3242700 -0.012938
1508  48.803024  0.811616 2018-12-28  2190500  0.009050
1509  49.123845  0.793644 2018-12-31  1719900  0.000974

[1509 rows x 5 columns]
1198
[[ 6.19718974e+01  0.00000000e+00  1.33980000e+06 -1.74659142e-02]
 [ 6.19718974e+01  0.00000000e+00  1.45720000e+06  6.16651659e-03]
 [ 6.19718974e+01  0.00000000e+00  1.43290000e+06  1.48901530e-03]
 ...
 [ 6.44897739e+01  4.69

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     72.392423  0.000000 2013-01-03   7448100  0.004232
2     72.392423  0.000000 2013-01-04  13587200  0.036339
3     72.392423  0.000000 2013-01-07   6989100 -0.001359
4     72.392423  0.000000 2013-01-08   5246100  0.007546
5     72.392423  0.000000 2013-01-09   7267200  0.020792
...         ...       ...        ...       ...       ...
1505  37.523468  2.825029 2018-12-24   3284000 -0.024704
1506  48.992228  2.956098 2018-12-26   3792400  0.039851
1507  52.857558  3.042805 2018-12-27   4101600  0.016073
1508  55.500453  3.004033 2018-12-28   3984000  0.011537
1509  58.413700  2.907317 2018-12-31   2731000  0.013222

[1509 rows x 5 columns]
1198
[[ 7.23924235e+01  0.00000000e+00  7.44810000e+06  4.23244275e-03]
 [ 7.23924235e+01  0.00000000e+00  1.35872000e+07  3.63391519e-02]
 [ 7.23924235e+01  0.00000000e+00  6.98910000e+06 -1.35864120e-03]
 ...
 [ 4.818426

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     44.727164  0.000000 2013-01-03  13148600 -0.000552
2     44.727164  0.000000 2013-01-04   7464200 -0.007212
3     44.727164  0.000000 2013-01-07   9429900 -0.014583
4     44.727164  0.000000 2013-01-08   8112900 -0.009080
5     44.727164  0.000000 2013-01-09  12977400  0.000000
...         ...       ...        ...       ...       ...
1505  37.537064  0.908531 2018-12-24   6288500 -0.011831
1506  49.031619  0.949350 2018-12-26  10063400  0.040810
1507  49.168646  0.941540 2018-12-27   8688600  0.000544
1508  51.686998  0.938573 2018-12-28   7369000  0.009740
1509  49.983193  0.930103 2018-12-31   4600600 -0.006212

[1509 rows x 5 columns]
1198
[[ 4.47271642e+01  0.00000000e+00  1.31486000e+07 -5.52437490e-04]
 [ 4.47271642e+01  0.00000000e+00  7.46420000e+06 -7.21227695e-03]
 [ 4.47271642e+01  0.00000000e+00  9.42990000e+06 -1.45825059e-02]
 ...
 [ 3.997634

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 332)           447536    
                                                                 
 global_average_pooling1d (  (None, 332)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                19980     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     66.693394  0.000000 2013-01-03  14937200  0.000772
2     66.693394  0.000000 2013-01-04  10376000  0.008134
3     66.693394  0.000000 2013-01-07  10242400  0.007119
4     66.693394  0.000000 2013-01-08  11800400  0.009267
5     66.693394  0.000000 2013-01-09  17552800  0.015134
...         ...       ...        ...       ...       ...
1505  29.106970  4.241238 2018-12-24   8617700 -0.020571
1506  44.326920  4.546150 2018-12-26  13499500  0.067497
1507  46.897970  4.613568 2018-12-27  10883000  0.013576
1508  45.536616  4.566884 2018-12-28   7381300 -0.008139
1509  47.082678  4.398535 2018-12-31   7976000  0.007608

[1509 rows x 5 columns]
1198
[[ 6.66933935e+01  0.00000000e+00  1.49372000e+07  7.71898938e-04]
 [ 6.66933935e+01  0.00000000e+00  1.03760000e+07  8.13441023e-03]
 [ 6.66933935e+01  0.00000000e+00  1.02424000e+07  7.11856960e-03]
 ...
 [ 5.963915

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     59.375105  0.000000 2013-01-03  14413200 -0.047883
2     59.375105  0.000000 2013-01-04  10458000  0.001922
3     59.375105  0.000000 2013-01-07   7804500  0.000000
4     59.375105  0.000000 2013-01-08   8196200 -0.013335
5     59.375105  0.000000 2013-01-09   5154300  0.018696
...         ...       ...        ...       ...       ...
1505  24.998042  7.370625 2018-12-24   3091000 -0.022917
1506  36.801896  7.669866 2018-12-26   4159300  0.043720
1507  39.387429  7.888447 2018-12-27   4295800  0.010709
1508  39.661376  7.680700 2018-12-28   3312700  0.001097
1509  42.639537  7.420650 2018-12-31   3123200  0.011628

[1509 rows x 5 columns]
1198
[[ 5.93751052e+01  0.00000000e+00  1.44132000e+07 -4.78830457e-02]
 [ 5.93751052e+01  0.00000000e+00  1.04580000e+07  1.92162726e-03]
 [ 5.93751052e+01  0.00000000e+00  7.80450000e+06  0.00000000e+00]
 ...
 [ 5.411696

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 32)            4736      
                                                                 
 global_average_pooling1d (  (None, 32)                0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                1980      
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     70.560664  0.000000 2013-01-03  13268200 -0.001805
2     70.560664  0.000000 2013-01-04  11427900  0.004619
3     70.560664  0.000000 2013-01-07  11799800 -0.011646
4     70.560664  0.000000 2013-01-08  14226400  0.006236
5     70.560664  0.000000 2013-01-09  10892200 -0.003850
...         ...       ...        ...       ...       ...
1505  20.097153  2.067170 2018-12-24  14262800 -0.039068
1506  33.197873  2.205944 2018-12-26  24887700  0.046673
1507  34.309618  2.252662 2018-12-27  22077000  0.004361
1508  32.800758  2.217472 2018-12-28  19710600 -0.011232
1509  32.883365  2.165510 2018-12-31  15807000  0.000293

[1509 rows x 5 columns]


C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


1198
[[ 7.05606642e+01  0.00000000e+00  1.32682000e+07 -1.80528488e-03]
 [ 7.05606642e+01  0.00000000e+00  1.14279000e+07  4.61943771e-03]
 [ 7.05606642e+01  0.00000000e+00  1.17998000e+07 -1.16460577e-02]
 ...
 [ 6.21825398e+01  7.14947103e-01  7.00060000e+06 -9.52692033e-04]
 [ 6.32127116e+01  6.81736596e-01  7.49530000e+06  1.42909123e-03]
 [ 5.78391954e+01  6.73040950e-01  8.52340000e+06 -4.53282410e-03]]
Length of inputs 1198
length of time-series - inputs (1198, 60, 4)
length of time-series - outputs (1198,)
Training Size (1198, 60, 4) (1198,)
Length of inputs 251
length of time-series - inputs (251, 60, 4)
length of time-series - outputs (251,)
Test Size (251, 60, 4) (251,)
Reloading Tuner from .\untitled_project\tuner0.json
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 32)            4736      
                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     72.092950  0.000000 2013-01-03  24227700 -0.002018
2     72.092950  0.000000 2013-01-04  24487700  0.017570
3     72.092950  0.000000 2013-01-07  24456900  0.001101
4     72.092950  0.000000 2013-01-08  19624200  0.001980
5     72.092950  0.000000 2013-01-09  25920600 -0.000660
...         ...       ...        ...       ...       ...
1505  20.814920  2.744690 2018-12-24  17009300 -0.021792
1506  34.730676  2.895069 2018-12-26  22542900  0.040622
1507  38.045705  2.945421 2018-12-27  20304700  0.011192
1508  37.645335  2.869320 2018-12-28  17963300 -0.002166
1509  40.195012  2.810082 2018-12-31  13237200  0.008126

[1509 rows x 5 columns]
1198
[[ 7.20929495e+01  0.00000000e+00  2.42277000e+07 -2.01794426e-03]
 [ 7.20929495e+01  0.00000000e+00  2.44877000e+07  1.75700690e-02]
 [ 7.20929495e+01  0.00000000e+00  2.44569000e+07  1.10149659e-03]
 ...
 [ 6.267355

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 452)           826256    
                                                                 
 global_average_pooling1d (  (None, 452)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                27180     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     55.765179  0.000000 2013-01-03   8910100 -0.006375
2     55.765179  0.000000 2013-01-04   6438000  0.003772
3     55.765179  0.000000 2013-01-07   6201400 -0.009603
4     55.765179  0.000000 2013-01-08   5866900  0.002774
5     55.765179  0.000000 2013-01-09   5055200 -0.000292
...         ...       ...        ...       ...       ...
1505  22.049033  1.980552 2018-12-24   6110300 -0.015149
1506  42.246704  2.167655 2018-12-26  10028300  0.052103
1507  46.112297  2.239251 2018-12-27   9881500  0.012967
1508  47.833130  2.213590 2018-12-28   9874000  0.005879
1509  51.015143  2.145477 2018-12-31   7005800  0.011011

[1509 rows x 5 columns]
1198
[[ 5.57651790e+01  0.00000000e+00  8.91010000e+06 -6.37516438e-03]
 [ 5.57651790e+01  0.00000000e+00  6.43800000e+06  3.77182159e-03]
 [ 5.57651790e+01  0.00000000e+00  6.20140000e+06 -9.60296427e-03]
 ...
 [ 6.943402

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 272)           301376    
                                                                 
 global_average_pooling1d (  (None, 272)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                16380     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date   Volume   Returns
1     85.021113  0.000000 2013-01-03  2462000 -0.002898
2     85.021113  0.000000 2013-01-04  1611000  0.005907
3     85.021113  0.000000 2013-01-07  2802000  0.003420
4     85.021113  0.000000 2013-01-08  4150000  0.009775
5     85.021113  0.000000 2013-01-09  2535000  0.002133
...         ...       ...        ...      ...       ...
1505  41.594247  0.458917 2018-12-24  1744400 -0.011077
1506  49.161167  0.478637 2018-12-26  2354600  0.024254
1507  52.361346  0.479448 2018-12-27  2486000  0.011472
1508  53.806659  0.470202 2018-12-28  2713600  0.005250
1509  55.268175  0.450545 2018-12-31  1450400  0.005223

[1509 rows x 5 columns]
1198
[[ 8.50211128e+01  0.00000000e+00  2.46200000e+06 -2.89752866e-03]
 [ 8.50211128e+01  0.00000000e+00  1.61100000e+06  5.90724238e-03]
 [ 8.50211128e+01  0.00000000e+00  2.80200000e+06  3.42024300e-03]
 ...
 [ 6.35601808e+01  3.29

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 392)           622496    
                                                                 
 global_average_pooling1d (  (None, 392)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                23580     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

[*********************100%%**********************]  1 of 1 completed
            RSI       ATR       Date    Volume   Returns
1     76.776775  0.000000 2013-01-03   9598300 -0.001413
2     76.776775  0.000000 2013-01-04  11631800  0.011386
3     76.776775  0.000000 2013-01-07   7548800 -0.002098
4     76.776775  0.000000 2013-01-08   9825300  0.000140
5     76.776775  0.000000 2013-01-09   7672800  0.004471
...         ...       ...        ...       ...       ...
1505  22.357813  3.818837 2018-12-24   7531900 -0.041851
1506  32.109627  3.885349 2018-12-26   9253000  0.031018
1507  33.730988  3.917824 2018-12-27   9918700  0.005509
1508  33.558369  3.780837 2018-12-28   6537200 -0.001100
1509  37.909004  3.673635 2018-12-31   7409900  0.013889

[1509 rows x 5 columns]
1198
[[ 7.67767746e+01  0.00000000e+00  9.59830000e+06 -1.41273000e-03]
 [ 7.67767746e+01  0.00000000e+00  1.16318000e+07  1.13855158e-02]
 [ 7.67767746e+01  0.00000000e+00  7.54880000e+06 -2.09842788e-03]
 ...
 [ 5.171528

C:\Users\user\AppData\Local\Temp\ipykernel_23460\2841010685.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock.Date = pd.to_datetime(df_stock.Date)
C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 60, 332)           447536    
                                                                 
 global_average_pooling1d (  (None, 332)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 60)                19980     
                                                                 
 dense_1 (Dense)             (None, 20)                1220      
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 21        
                                                        

In [62]:
total_predicted_returns.to_csv("LSTM_total_predicted_returns.csv")

In [64]:
total_predicted_returns

JNJ       Date       NVO       WMT       JPM       XOM       UNH  \
0    1.187479 2018-01-02  0.400482  0.851292  1.276625  0.621484  2.294138   
1    1.187405 2018-01-03  0.400483  0.850694  1.275808  0.624629  2.294166   
2    1.187378 2018-01-04  0.400508  0.851775  1.275522  0.626881  2.294266   
3    1.187370 2018-01-05  0.400309  0.853269  1.276259  0.630076  2.294626   
4    1.187713 2018-01-08  0.400484  0.854592  1.275959  0.633020  2.295369   
..        ...        ...       ...       ...       ...       ...       ...   
246  1.187132 2018-12-24  0.400016  0.844945  1.273794  0.922194  2.328972   
247  1.187102 2018-12-26  0.399865  0.844872  1.272514  0.928911  2.330931   
248  1.187556 2018-12-27  0.399684  0.845412  1.273991  0.934888  2.332260   
249  1.187314 2018-12-28  0.399941  0.845919  1.274330  0.942548  2.333333   
250  1.186751 2018-12-31  0.399778  0.845322  1.275024  0.950001  2.334056   

            V       TSM       LLY      HSBC      META      TSLA      NVDA  \
0    1.294258  0.405146  1.450552  0.481816  1.822085  0.585421  0.387131   
1    1.294105  0.405186  1.449007  0.481994  1.822085  0.583733  0.387053   
2    1.294041  0.405329  1.448271  0.482068  1.822085  0.582224  0.387071   
3    1.293972  0.405153  1.442085  0.481276  1.822085  0.581937  0.387092   
4    1.294471  0.405125  1.441783  0.481733  1.822085  0.580866  0.386907   
..        ...       ...       ...       ...       ...       ...       ...   
246  1.293092  0.404957  1.443397  0.481059  1.822085  0.720744  0.390519   
247  1.292784  0.404556  1.445079  0.480850  1.822085  0.719267  0.390622   
248  1.293167  0.405026  1.445903  0.480990  1.822085  0.724933  0.390542   
249  1.292291  0.404412  1.446424  0.480522  1.822085  0.721980  0.390401   
250  1.292656  0.404821  1.447963  0.480665  1.822085  0.720867  0.390385   

         AMZN     GOOGL      GOOG      MSFT      AAPL  
0    1.116622  0.633493  0.511192  1.013067  0.505889  
1    1.115542  0.631531  0.512316  1.012728  0.506011  
2    1.115245  0.629246  0.510768  1.012687  0.506570  
3    1.114246  0.628038  0.506848  1.012696  0.506658  
4    1.116062  0.629064  0.510714  1.012563  0.507224  
..        ...       ...       ...       ...       ...  
246  1.114677  0.684076  0.487627  1.012886  0.507017  
247  1.111705  0.685611  0.483614  1.012709  0.507593  
248  1.113112  0.679355  0.485190  1.012827  0.508079  
249  1.109814  0.679753  0.485605  1.012765  0.508645  
250  1.111068  0.679225  0.483724  1.013070  0.509039  

[251 rows x 19 columns]